services:
  app:
    build:
      context: ./app
    container_name: django-app
    env_file:
      - .env
    volumes:
      - ./static_volume:/src/DSA_site_validator/validator/staticfiles
      - ./db_volume:/src/DSA_site_validator/validator/db  
      - ./media:/src/DSA_site_validator/validator/media
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - ./static_volume:/src/DSA_site_validator/validator/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network


networks:
  app-network:
