# Generated by Django 5.1.3 on 2024-11-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="bonus_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
